# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: NorthBoat's Blog
subtitle: ''
description: ''
keywords:
author: NorthBoat
language: en
timezone: ''

navbar:
  blog_title: NorthBoat's Blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill', name: 'Home' }
    - { key: 'categorie', link: '/categories/', icon: 'iconfont icon-book', name: 'Categories' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: 'Tags' }
    - {
        key: 'Docs',
        icon: 'iconfont icon-books',
        submenu: [
            { key: 'C/C++', link: 'https://northboat-docs.vercel.app/dev/c/' },
	    { key: 'Java', link: 'https://northboat-docs.vercel.app/dev/java/' },
            { key: 'Front End', link: 'https://northboat-docs.vercel.app/dev/frontend/' },
	    { key: 'DevOps', link: 'https://northboat-docs.vercel.app/dev/devops/' },
            { key: 'DataStruct', link: 'https://northboat-docs.vercel.app/major/datastruct/' },
	    { key: 'Network', link: 'https://northboat-docs.vercel.app/major/network/' },
            { key: 'Operating System', link: 'https://northboat-docs.vercel.app/major/operating/' },
	    { key: 'Organization', link: 'https://northboat-docs.vercel.app/major/organization/' },
            { key: 'Mathematics', link: 'https://northboat-docs.vercel.app/ai/math/' },
	    { key: 'Python', link: 'https://northboat-docs.vercel.app/ai/python/' },
            { key: 'Machine Learning', link: 'https://northboat-docs.vercel.app/ai/ml/' },
	    #{ key: 'Deep Learning', link: 'https://northboat-docs.vercel.app/ai/dl/' }, 
       ]
      }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'archives', link: '/archives/', icon: 'iconfont icon-codeforces', name: 'Archives' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-addrcard', name: 'About' }


# 懒加载模式
lazyload:
  enable: true
  loading_img: /static/loading.gif
  onlypost: false
  offset_factor: 2

font:  # 主题字体配置
  font_size: 16px        # 全局字号
  font_family:           # 全局字体族
  code_font_size: 85%    # 代码的字号


# 页脚
footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

# 暗色模式
dark_mode:
  enable: true
  default: auto # 可选 light/dark


# 主页配置
index:
  banner_img: /static/used.jpg
  # 滚动条
  slogan:
    enable: true
    text: 愿我早逝，且无来生
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
  post_url_target: _self # 打开方式 blank
  # 文章信息
  post_meta:
    date: true
    category: true
    tag: true

# 打印效果
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果

# 网页图标
favicon: /static/favicon.ico


about:
  avatar: /static/logo.jpg
  name: "NorthBoat"
  intro: "984.5混子"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/NorthBoat', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/static/wechat.png' }

tag:
  banner_img: /static/train.gif

links:
  enable: true
  banner_img: /static/mountain.jpg
  items:
    - { title: 'NEUQ EKeeper House', intro: '给部门搭的资源站', link: 'https://neuq.club/', avatar: '/static/ekeeper.jpg' }
    - { title: "My Study Room", intro: '我的自习室', link: 'https://northboat-docs.vercel.app/', avatar: '/static/favicon.ico' }


post:
  banner_img: /static/bear.png


archive:
  banner_img: /static/kelamayi.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3



category:
  enable: true
  banner_img: /static/sea.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3

















